### PR TITLE
Add cmakelint script to check cmake format.

### PR DESCRIPTION
**Pull request by junaruga**
This PR is related to https://github.com/COMBINE-lab/salmon/pull/276#issue-210022241 .

It is to add lintcheck for cmake files.

## How to use

```
$ pip3 install cmakelint

$ which cmakelint
/path/to/cmakelint

$ ./scripts/lint.sh
```

Every CMakeLists.txt or *.cmake file in this repository is target for the check.
Right now I only modified `./CMakeLists.txt` to show for the example, and changed the permission of the executable bit file. Maybe the executable bit is not necessary.

### CODE REVIEW

**Comment by junaruga** [comment]
cmakelint can adjust indent space number. 2 or 4 spaces preferably according to KDE cmake codding style.
https://community.kde.org/Policies/CMake_Coding_Style#Indentation

Seeing current files in this repository:
*.cpp: 2 spaces indent
*.sh: 4 spaces indent ?
.travis.yml: 2 spaces indent

So, *.cmake or CMakeLists.txt: 2 spaces indent looks good?

**Comment by junaruga** [comment]
You can see the added cmake file lint test case as allowed failures on Travis here.
It's good to see how the `cmakelint` works.
https://travis-ci.org/COMBINE-lab/salmon/builds/427929967

**Comment by rob-p** [comment]
Ohh man ... there are a bunch of lint warnings to fix (at least those not in modules we include).  Thanks again for the PR!

**Comment by junaruga** [comment]
@rob-p thanks for merging! I wish the Travis CI's lint task helps to fix the warnings, and keep the consistent format of `cmake` files!
Eventually we will see the green color passing the lint check on the Travis CI page :)

**Pull request merged**
