### PR TITLE
Use installed cereal and stadenio libraries if available.

### PR DESCRIPTION
**Pull request by gaberoo**
There's been some issues with compiling salmon on macOS for some time now (see also https://github.com/brewsci/homebrew-bio/pull/528). In the current version, I was running into two compile errors on macOS:

1) problems with staden & Clang
2) problems with linking to boost static libraries

I could fix (1) by installing staden separately and then using that install in salmon. I've included the respective Find***.cmake files.

(2) is an easy fix by modifying the `CMakeLists.txt`. Is there any particular preference for using static libraries? This is a rather small patch and could be done in a Homebrew formula, if you prefer static boost libraries.

Otherwise, this PR are just suggestions. If you have changes that better conform to you style, that's fine by me.

Thanks,
Gabriel

### CODE REVIEW

**Comment by rob-p** [comment]
Hi @gaberoo ,

  Thanks for this PR --- we'll review it ASAP.  The build difficulties under OSX are interesting, as we both build it locally under OSX, and have it built under OSX (using clang) for bioconda.  I'm curious what is unique about the homebrew/sci environment.

**Comment by gaberoo** [comment]
Hi @rob-p,

Great, thanks! The linking problem seems to have something to do with Homebrew boost. 

Additionally, there was a problem with the build-stage compilation of stadeniolib using Clang. I don't think this had anything to do with Brew, but rather the compile flags passed on from CMake. But I figured a Findlibstadenio.cmake doesn't hurt in any case.

**Comment by rob-p** [comment]
This is failing on our local drone CI during runtime.  The log output is :

```
+ echo "[Testing quant]"
[Testing quant]
+ ./.drone/test_quant.sh
Holy build box activated
Prefix: /hbb_exe
CFLAGS: -g -O2 -fvisibility=hidden -I/hbb_exe/include 
LDFLAGS: -L/hbb_exe/lib -static-libstdc++
STATICLIB_CFLAGS: -g -O2 -fvisibility=hidden -I/hbb_exe/include 
SHLIB_CFLAGS: -g -O2 -fvisibility=hidden -I/hbb_exe/include 
SHLIB_LDFLAGS: -L/hbb_exe/lib -static-libstdc++
[Drone test] current path : /drone/src/github.com/COMBINE-lab/salmon
[Drone test] making quant test directory
[Drone test] run nextflow pipeline
N E X T F L O W  ~  version 0.29.1
Launching `tests/test_quant.nf` [curious_gilbert] - revision: 4f25b30301
[warm up] executor > local
[91/922fac] Submitted process > buildIndex
ERROR ~ Error executing process > 'buildIndex'
Caused by:
  Process `buildIndex` terminated with an error exit status (127)
Command executed:
  /drone/src/github.com/COMBINE-lab/salmon/bin/salmon index -t Homo_sapiens.GRCh37.75.cdna.pc.fa -i nfindex
Command exit status:
  127
Command output:
  (empty)
Command error:
  /drone/src/github.com/COMBINE-lab/salmon/bin/salmon: error while loading shared libraries: libjemalloc.so.2: cannot open shared object file: No such file or directory
Work dir:
  /drone/src/github.com/COMBINE-lab/salmon/work/91/922facec25da43edd4a2ce82f2289d
Tip: when you have fixed the problem you can continue the execution appending to the nextflow command line the option `-resume`
-- Check '.nextflow.log' file for detail
```

So, it seems to be due to failure to find the dynamic shared library for jemalloc.  Any idea why that might be?

**Comment by gaberoo** [comment]
OK, So there seems to be a problem with using the shared libraries on your CI. I've dropped the specific commit that removes the requirement for static libraries to see if it builds.

**Comment by gaberoo** [comment]
This in the compile error I get for the Staden package, FYI:

```
 ❯ make VERBOSE=1                                                                                                                [12:30:35]
/usr/local/Cellar/cmake/3.13.4/bin/cmake -S/Users/gabriel/Projects/salmon-0.13.1 -B/Users/gabriel/Projects/salmon-0.13.1/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/local/Cellar/cmake/3.13.4/bin/cmake -E cmake_progress_start /Users/gabriel/Projects/salmon-0.13.1/build/CMakeFiles /Users/gabriel/Projects/salmon-0.13.1/build/CMakeFiles/progress.marks
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/Makefile2 all
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/libcereal.dir/build.make CMakeFiles/libcereal.dir/depend
cd /Users/gabriel/Projects/salmon-0.13.1/build && /usr/local/Cellar/cmake/3.13.4/bin/cmake -E cmake_depends "Unix Makefiles" /Users/gabriel/Projects/salmon-0.13.1 /Users/gabriel/Projects/salmon-0.13.1 /Users/gabriel/Projects/salmon-0.13.1/build /Users/gabriel/Projects/salmon-0.13.1/build /Users/gabriel/Projects/salmon-0.13.1/build/CMakeFiles/libcereal.dir/DependInfo.cmake --color=
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/libcereal.dir/build.make CMakeFiles/libcereal.dir/build
make[2]: Nothing to be done for `CMakeFiles/libcereal.dir/build'.
[  8%] Built target libcereal
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/libstadenio.dir/build.make CMakeFiles/libstadenio.dir/depend
cd /Users/gabriel/Projects/salmon-0.13.1/build && /usr/local/Cellar/cmake/3.13.4/bin/cmake -E cmake_depends "Unix Makefiles" /Users/gabriel/Projects/salmon-0.13.1 /Users/gabriel/Projects/salmon-0.13.1 /Users/gabriel/Projects/salmon-0.13.1/build /Users/gabriel/Projects/salmon-0.13.1/build /Users/gabriel/Projects/salmon-0.13.1/build/CMakeFiles/libstadenio.dir/DependInfo.cmake --color=
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/libstadenio.dir/build.make CMakeFiles/libstadenio.dir/build
[  9%] Performing configure step for 'libstadenio'
cd /Users/gabriel/Projects/salmon-0.13.1/external/staden-io_lib && ./configure --enable-shared=no --without-libcurl --prefix=/Users/gabriel/Projects/salmon-0.13.1/external/install LDFLAGS= CFLAGS= CC=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc CXX=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
checking for a BSD-compatible install... /usr/local/bin/ginstall -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/local/bin/gmkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking for gcc... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... configure: error: in `/Users/gabriel/Projects/salmon-0.13.1/external/staden-io_lib':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
make[2]: *** [libstadenio-prefix/src/libstadenio-stamp/libstadenio-configure] Error 1
make[1]: *** [CMakeFiles/libstadenio.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by gaberoo** [comment]
Hey @rob-p,

OK, I think the changes should pass CI now in theory. Basically I patched the `CMakeLists.txt` file to only download and build those libraries which are not found on the system. If they aren't found, then you have the same behaviour as before.

Also, you can now activate the use of shared libraries by setting `USE_SHARED_LIBS=1` on cmake. This should work quite nicely for a Homebrew formula.

**Comment by rob-p** [comment]
Not sure why the drone CI isn't completing, but I just changed the base to develop and am going to merge this now --- all the changes look great.  Thanks again for the PR! Hopefully that will make the drone CI work.

**Comment by rob-p** [comment]
Hi @gaberoo,

  I rebased this in develop since this is where we make changes, so that this will be in the next release.  There was one change I had to make.  There was a place where a string variable was being checked to determine the existence of a library (e.g. `if (${SUFFARRAY_LIB})` I believe).  It seems CMake interprets even the empty string as TRUE here, so I had to change this to the corresponding `FOUND` variable.  Otherwise, the changes all seem to have worked beautifully.  Thanks again.

**Comment by gaberoo** [comment]
Sounds good! Once it’s in the next release, we can see if we can get the Homebrew formula working.

**Comment by sjackman** [comment]
Thank you both very much for working on this issue! I'm looking forward to having Salmon updated in Brewsci/bio. Enjoy your weekend!

**Pull request merged**
