### PR TITLE
src/CMakeLists.txt: Disable RPATH on Mac

### PR DESCRIPTION
**Pull request by sjackman**
Warning: This PR is entirely untested. The goal is to make the `salmon` bottle relocatable on Homebrew and Linuxbrew.

### CODE REVIEW

**Comment by rob-p** [comment]
Thanks, @sjackman!  Can we move this over to the develop branch (since that's where I'm finishing up work on 0.7.0).

**Comment by sjackman** [comment]
Currently the installed `salmon` executable has `RPATH` set, which isn't needed on Mac OS, which uses absolute paths to dynamic libraries.

```
❯❯❯ otool -l /usr/local/bin/salmon |grep -A2 RPATH
          cmd LC_RPATH
      cmdsize 56
         path /usr/local/Cellar/salmon/0.6.0_1/bin (offset 12)
--
          cmd LC_RPATH
      cmdsize 56
         path /usr/local/Cellar/salmon/0.6.0_1/lib (offset 12)
--
          cmd LC_RPATH
      cmdsize 32
         path @executable_path (offset 12)
```

**Comment by sjackman** [comment]
> Thanks, @sjackman! Can we move this over to the develop branch (since that's where I'm finishing up work on 0.7.0).

Not without closing and reopening this PR (as far as I know), but really I just wanted a forum to discuss and solve the issue.

**Comment by rob-p** [comment]
Yea, I think it's fine here.  There are too many RPATH options on OSX e.g ([this](https://cmake.org/cmake/help/v3.0/prop_tgt/MACOSX_RPATH.html)).

**Comment by sjackman** [comment]
Unrelated, I hope, but Travis:
```
ERROR: Intel TBB NOT found!
```
https://travis-ci.org/COMBINE-lab/salmon/builds/151874140#L543

**Comment by sjackman** [comment]
No luck with this patch.
```
❯❯❯ cmake -DCMAKE_INSTALL_PREFIX:PATH=$HOME/tmp/salmon ..
❯❯❯ make
❯❯❯ make install
❯❯❯ otool -l /Users/sjackman/tmp/salmon/bin/salmon |grep -A2 RPATH
          cmd LC_RPATH
      cmdsize 48
         path /Users/sjackman/tmp/salmon/bin (offset 12)
--
          cmd LC_RPATH
      cmdsize 48
         path /Users/sjackman/tmp/salmon/lib (offset 12)
--
          cmd LC_RPATH
      cmdsize 32
         path @executable_path (offset 12)
```

**Comment by rob-p** [comment]
At least the Travis issue was unrelated (I just restarted it).

**Comment by sjackman** [comment]
> Default RPATH settings
By default if you don't change any RPATH related settings, CMake will link the executables and shared libraries with full RPATH to all used libraries in the build tree. When installing, it will clear the RPATH of these targets so they are installed with an empty RPATH.

https://cmake.org/Wiki/CMake_RPATH_handling#Default_RPATH_settings

We want this default `RPATH` behaviour from `cmake`. I'm unsure why we're getting non-default behaviour.

**Comment by rob-p** [comment]
I placed the explicit commands they have there into the CMakeLists.txt and still get

```
~/S/build ❯❯❯ otool -l ../bin/salmon | grep -A2 RPATH
          cmd LC_RPATH
      cmdsize 40
         path /Users/rob/Salmon/bin (offset 12)
--
          cmd LC_RPATH
      cmdsize 40
         path /Users/rob/Salmon/lib (offset 12)
--
          cmd LC_RPATH
      cmdsize 32
         path @executable_path (offset 12)
```

**Comment by rob-p** [comment]
*Ah ha*!! It's coming from [https://github.com/COMBINE-lab/salmon/blob/develop/cmake/PostInstall.cmake](https://github.com/COMBINE-lab/salmon/blob/develop/cmake/PostInstall.cmake).

**Comment by rob-p** [comment]
That seems to fix it!  Any thoughts on these other incantations I have there?

```
##
#  This ensures that the salmon executable should work with or without `make install`
##
# Grumble grumble . . . OSX
if (APPLE)
    # only attempt install_name_tool for tbb if we installed it
    if (${TBB_LIBRARY_DIRS} MATCHES ${GAT_SOURCE_DIR}/external/install/lib)
        add_custom_command(TARGET salmon
            POST_BUILD
            COMMAND install_name_tool -change libtbb.dylib @rpath/libtbb.dylib ${GAT_SOURCE_DIR}/build/src/salmon
            COMMAND install_name_tool -change libtbbmalloc.dylib @rpath/libtbbmalloc.dylib ${GAT_SOURCE_DIR}/build/src/salmon
            COMMAND install_name_tool -change libtbbmalloc_proxy.dylib @rpath/libtbbmalloc_proxy.dylib ${GAT_SOURCE_DIR}/build/src/salmon
            COMMAND install_name_tool -add_rpath  ${GAT_SOURCE_DIR}/external/install/lib ${GAT_SOURCE_DIR}/build/src/salmon
            )
        add_custom_command(TARGET unitTests
            POST_BUILD
            COMMAND install_name_tool -change libtbb.dylib @rpath/libtbb.dylib ${GAT_SOURCE_DIR}/build/src/unitTests
            COMMAND install_name_tool -change libtbbmalloc.dylib @rpath/libtbbmalloc.dylib ${GAT_SOURCE_DIR}/build/src/unitTests
            COMMAND install_name_tool -change libtbbmalloc_proxy.dylib @rpath/libtbbmalloc_proxy.dylib ${GAT_SOURCE_DIR}/build/src/unitTests
            COMMAND install_name_tool -add_rpath  ${GAT_SOURCE_DIR}/external/install/lib ${GAT_SOURCE_DIR}/build/src/unitTests
            )
    endif()
else()
    # related to complete static linking --- on hold    
    set (BOOST_THREAD_LIBRARY)
endif()

```

**Comment by sjackman** [comment]
Yeah! It works for me too! No more `RPATH`!

**Comment by sjackman** [comment]
I would suggest getting rid of the incantation. `cmake` is supposed to handle setting the path of the libraries.

**Comment by rob-p** [comment]
OK, but in that case, it doesn't find libtbb (if it was built by salmon's build) unless the path is in either `DYLD_LIBRARY_PATH` or `DYLD_FALLBACK_LIBRARY_PATH`.

**Comment by sjackman** [comment]
On my system, `cmake` found (somehow, I didn't tell it) TBB that is installed in `/usr/local/opt/tbb/lib/libtbb.dylib`. What does `otool -L salmon` report on your system after `make install`?

```sh
❯❯❯ otool -L ~/tmp/salmon/bin/salmon
/Users/sjackman/tmp/salmon/bin/salmon:
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
	/usr/lib/libbz2.1.0.dylib (compatibility version 1.0.0, current version 1.0.5)
	/usr/local/opt/tbb/lib/libtbb.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/tbb/lib/libtbbmalloc.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.1.0)
```

**Comment by rob-p** [comment]
Mine reports:

```
~/S/s/build ❯❯❯ otool -L ../bin/salmon
../bin/salmon:
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
	/usr/lib/libbz2.1.0.dylib (compatibility version 1.0.0, current version 1.0.5)
	@rpath/libtbb.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libtbbmalloc.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.1.0)
```

I think the difference may be that in my build, the salmon build system d/l and installed libtbb (which it does if it's not present on the system already).

**Comment by sjackman** [comment]
I'm surprised that the `@rpath` showed up, when I thought that we had disabled that.

So long as `brew install salmon` works on Mac, I wouldn't worry about downloading and installing dependencies on Mac.

**Comment by rob-p** [comment]
Is it possible to have homebrew pull from the head of develop before I tag the release to make sure this fix works under homebrew science?

**Comment by sjackman** [comment]
I'm testing it now.
```sh
brew edit salmon
```
Then add
```
  patch do
    url "https://patch-diff.githubusercontent.com/raw/COMBINE-lab/salmon/pull/70.patch"
    sha256 "7129eac8591ad954cca30576519071b1f5ea2a36206f973a1aef0bc1eb5d20da"
```
Then
```
brew install salmon --build-bottle
brew bottle salmon --json -v
```

**Comment by rob-p** [comment]
Great; this will test against develop, right?  Not master.  Because 0.7.0 is coming from develop.

**Comment by sjackman** [comment]
I tested against the released 0.6.0 tarball.

**Comment by sjackman** [comment]
Success!

```
❯❯❯ brew bottle salmon --json -v
==> Detecting if salmon-0.6.0_1.el_capitan.bottle.1.tar.gz is relocatable...
./salmon-0.6.0_1.el_capitan.bottle.1.tar.gz
  bottle do
    cellar :any
    revision 1
    sha256 "8c646bf4e16567180377628fb99fce3a98eeec8b9a55e9140699e0d76b423810" => :el_capitan
  end
```

**Comment by sjackman** [comment]
I'd like to release a relocatable bottle of 0.6.0. Would you like to merge this PR and tag Salmon 0.6.1, or would you prefer that I release a revised bottle of Salmon 0.6.0. The revised bottle has the version number `0.6.0_1`.

**Comment by rob-p** [comment]
Awesome!  I have a slight preference for 0.6.0_1, since there's no real change to the *codebase* from 0.6.0.  Is it easy to test this against develop (can I tell it to pull from there)?  I'd like to test that as well so that, hopefully, I can get 0.7.0 out the door and we can get it in homebrew science by Tues. when the students will be using it.

**Comment by sjackman** [comment]
Here's the PR for 0.6.0_1 https://github.com/Homebrew/homebrew-science/pull/4053

**Comment by sjackman** [comment]
If you'd like to commit the equivalent of this PR into develop, I can test it for you. Give me the PR or commit SHA1, and I'll test it.

**Comment by rob-p** [comment]
Great!  One thing I found is that if I `INSTALL` the unitTests like I've been doing, they fail to find the appropriate libraries (again if they were fetched).  I pushed a fix for this in develop.  Basically, you  just have to copy, not install, the unit test executable.  That's done with the following incantation:

```
add_custom_command(TARGET unitTests POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E copy $<TARGET_FILE:unitTests> ${GAT_SOURCE_DIR}/tests/$<TARGET_FILE_NAME:unitTests>
    COMMENT "Copying unitTests"
)
```

I don't know if this is necessary for homebrew or not, since it has no effect on the salmon binary itself.

**Comment by rob-p** [comment]
You can pull from this commit sha on develop to test the equivalent changes on that branch `bd7096e0fa055e0a71ab03a52d99977bcb61c905`.  If this works, I think I'm pretty much good to go for the release.  Just doing some last minute clean up and finishing up the release notes.

**Comment by sjackman** [comment]
The relocatable Salmon bottle 0.6.0_1 is merged!

**Comment by rob-p** [comment]
nice; that was fast!

**Comment by sjackman** [comment]
I'm testing now whether `develop` bd7096e0fa055e0a71ab03a52d99977bcb61c905 is relocatable.

**Comment by sjackman** [comment]
Success!
```
==> Detecting if salmon-HEAD-bd7096e_2.el_capitan.bottle.tar.gz is relocatable...
./salmon-HEAD-bd7096e_2.el_capitan.bottle.tar.gz
  bottle do
    cellar :any
    sha256 "467695cb8b24ef5806a2087bfe58cc77b924b82cb110391a23513a05d9aac34e" => :el_capitan
  end
```

**Comment by rob-p** [comment]
Awesome!  Thanks so much for all your help, Shaun!  Once 0.7.0 is tagged, I'll submit the homebrew science PR (I'll mention you so you're aware).

**Pull request closed without merging**
